### PR TITLE
Arrays are not objects

### PR DESCRIPTION
**Pull request by fiatjaf**
currently when some value in the `host` is an Array, what happens is that its indexes are treated as keys in an object, so the following happens:

``` javascript
var host = {
  items: [
    "lemon",
    "mango",
    "apple"
  ]
}

var newHost = update(host, {
  items: ["strawberry"]
})

newHost.items.length == 3
newHost.items[0] == "strawberry"
newHost.items[1] == "mango"
newHost.items[1] == "apple"
```

### CODE REVIEW

**Comment by fiatjaf** [comment]
I understand the solution to this is to update with a function, not with the target array itself, but I still think the default should be to entirely replace the array.

If not, at least this behavior should be clear from the documentation.

**Comment by AlexGalays** [comment]
Hello @fiatjaf and sorry for the late reply, I was on holiday. 
I think what you're saying makes total sense, let me play a bit with it and I will merge it.

**Comment by AlexGalays** [comment]
Merged in 0.1.1

**Comment by AlexGalays** [comment]
Ah, just encountered the bug on an app using version 1.0.0, thanks again :)

**Pull request closed without merging**
